# Generated by Django 5.2.1 on 2025-06-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_address_customer_cascade'),
        ('accounts', '0006_rename_state_address_province_address_pelak_and_more'),
    ]

    operations = [
    ]
