# Generated by Django 5.2.1 on 2025-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rebuild_group_permission_tables_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('other', 'Other')], default='email', help_text='How the user logged in or registered (email, google, etc.)', max_length=20),
        ),
    ]
