# Generated by Django 5.2.1 on 2025-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='vahed',
            field=models.CharField(blank=True, help_text='واحد', max_length=20, null=True),

        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.CharField(default='', help_text='واحد', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='pelak',
            field=models.CharField(blank=True, help_text='پلاک', max_length=20, null=True),
        ),
    ]
