# Generated by Django 5.2 on 2025-07-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_address_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(help_text='Name of the person receiving the package', max_length=100),
        ),
    ]
