# Generated by Django 5.2 on 2025-07-12 04:40

from django.db import migrations


def update_receiver_names(apps, schema_editor):
    Address = apps.get_model('accounts', 'Address')
    Customer = apps.get_model('accounts', 'Customer')
    
    # Update addresses with empty receiver_name
    addresses_to_update = Address.objects.filter(receiver_name='')
    
    for address in addresses_to_update:
        # Use customer's full name as receiver name
        customer = address.customer
        receiver_name = f"{customer.first_name} {customer.last_name}".strip()
        
        # If customer has no name, use email
        if not receiver_name:
            receiver_name = customer.email.split('@')[0]
        
        address.receiver_name = receiver_name
        address.save()


def reverse_update_receiver_names(apps, schema_editor):
    # No reverse operation needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_address_receiver_name'),
    ]

    operations = [
        migrations.RunPython(update_receiver_names, reverse_update_receiver_names),
    ]
