# Generated by Django 5.2 on 2025-07-12 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_address_pelak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', help_text='Phone number', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_postal_code', message='Postal code must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
