# Generated by Django 5.2 on 2025-11-12 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_address_phone_alter_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address attempted', max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent')),
                ('success', models.BooleanField(default=False, help_text='Whether login was successful')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Invalid Credentials'), ('account_locked', 'Account Locked'), ('rate_limited', 'Rate Limited'), ('captcha_required', 'CAPTCHA Required'), ('verification_required', 'Verification Required')], help_text='Reason for failure', max_length=100)),
                ('security_tier', models.IntegerField(choices=[(1, 'Tier 1: Normal'), (2, 'Tier 2: Warning'), (3, 'Tier 3: CAPTCHA'), (4, 'Tier 4: Email Verification'), (5, 'Tier 5: Account Lock')], default=1, help_text='Security tier triggered')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('country_code', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_lo_email_f32d13_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_lo_ip_addr_a49186_idx'), models.Index(fields=['-created_at'], name='accounts_lo_created_144710_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('ip_address', models.GenericIPAddressField(help_text='IP that triggered code generation')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Code expiration time')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum verification attempts allowed')),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_ve_email_5aef8b_idx'), models.Index(fields=['code', 'email'], name='accounts_ve_code_f47de7_idx'), models.Index(fields=['-created_at'], name='accounts_ve_created_45c04d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email of locked account', max_length=254)),
                ('locked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When lock auto-expires')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether lock is currently active')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_by', models.CharField(blank=True, choices=[('auto_expire', 'Automatic Expiration'), ('email_link', 'Email Unlock Link'), ('admin', 'Admin Override'), ('password_reset', 'Password Reset')], help_text='How the lock was released', max_length=50)),
                ('unlock_token', models.CharField(db_index=True, help_text='Secure token for unlock link', max_length=64, unique=True)),
                ('unlock_token_expires', models.DateTimeField(help_text='When unlock token expires')),
                ('reason', models.CharField(choices=[('too_many_attempts', 'Too Many Failed Attempts'), ('suspicious_location', 'Suspicious Location'), ('distributed_attack', 'Distributed Attack Detected'), ('manual_lock', 'Manual Security Lock')], default='too_many_attempts', help_text='Why account was locked', max_length=100)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of failed attempts that triggered lock')),
                ('ip_addresses', models.JSONField(default=list, help_text='IPs involved in failed attempts')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer account (if exists)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Lock',
                'verbose_name_plural': 'Account Locks',
                'ordering': ['-locked_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='accounts_ac_email_c6553e_idx'), models.Index(fields=['unlock_token'], name='accounts_ac_unlock__a831fa_idx'), models.Index(fields=['is_active', '-locked_at'], name='accounts_ac_is_acti_66a1ad_idx')],
            },
        ),
    ]
