# Generated by Django 5.2 on 2025-11-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_loginattempt_verificationcode_accountlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token_version',
            field=models.IntegerField(default=0, help_text='Increment this to invalidate all existing JWT tokens immediately'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Unique identifier for this session (from JWT jti claim)', max_length=255, unique=True)),
                ('refresh_token_jti', models.CharField(blank=True, help_text='JTI of the refresh token for this session', max_length=255, null=True, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Device name (e.g., "iPhone 14 Pro", "iPad Air")', max_length=255)),
                ('device_type', models.CharField(blank=True, help_text='Device type: ios, android, web, etc.', max_length=50)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier (e.g., identifierForVendor on iOS)', max_length=255)),
                ('app_version', models.CharField(blank=True, help_text='App version (e.g., "1.0.5")', max_length=50)),
                ('os_version', models.CharField(blank=True, help_text='OS version (e.g., "iOS 17.1")', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device')),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string')),
                ('location_city', models.CharField(blank=True, help_text='Approximate city (from IP geolocation)', max_length=100)),
                ('location_country', models.CharField(blank=True, help_text='Country (from IP geolocation)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current session (for UI display)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created (user logged in)')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time this session was used')),
                ('expires_at', models.DateTimeField(help_text='When this session expires (refresh token expiration)')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this session was manually revoked', null=True)),
                ('revoked_reason', models.CharField(blank=True, help_text='Reason for revocation: user_action, password_change, account_deletion, etc.', max_length=100)),
                ('user', models.ForeignKey(help_text='User who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'), models.Index(fields=['session_key'], name='accounts_us_session_511f42_idx'), models.Index(fields=['refresh_token_jti'], name='accounts_us_refresh_61d6c4_idx'), models.Index(fields=['device_id'], name='accounts_us_device__a80fba_idx')],
            },
        ),
    ]
