# Generated by Django 5.2 on 2025-11-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customer_token_version_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token_version',
            field=models.IntegerField(blank=True, default=0, help_text='Increment this to invalidate all existing JWT tokens immediately', null=True),
        ),
    ]
