# Generated by Django 5.2 on 2025-07-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_fix_user_fk_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_logs', to='suppliers.user'),
        ),
        migrations.AlterField(
            model_name='deletedsupplier',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_suppliers', to='suppliers.user'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='suppliers.user'),
        ),
        migrations.AlterField(
            model_name='supplieradmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_admin_profile', to='suppliers.user'),
        ),
    ]
