# Generated by Django 5.2.1 on 2025-07-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_backuplog_created_by_and_more'),
    ]

    operations = [
    ]
