# Generated by Django 5.2 on 2025-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvitation',
            name='token',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
