# Generated by Django 5.2.1 on 2025-05-24 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_backuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original ID of the supplier')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deleted supplier',
                'verbose_name_plural': 'deleted suppliers',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
