# Generated by Django 5.2.1 on 2025-07-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_remove_old_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier Invitation', 'verbose_name_plural': 'Supplier Invitations'},
        ),
        migrations.RemoveConstraint(
            model_name='supplierinvitation',
            name='unique_active_invitation',
        ),
        migrations.RenameField(
            model_name='supplierinvitation',
            old_name='email_sent',
            new_name='is_sent',
        ),
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='owner_first_name',
        ),
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='owner_last_name',
        ),
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='store_username',
        ),
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who sent this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='suppliers.user'),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this invitation'),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='owner_name',
            field=models.CharField(blank=True, help_text="Owner's full name", max_length=100),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvitation',
            name='address',
            field=models.TextField(blank=True, help_text='Store address'),
        ),
        migrations.AlterField(
            model_name='supplierinvitation',
            name='email',
            field=models.EmailField(help_text="Supplier's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='supplierinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Email Sent'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierinvitation',
            name='store_name',
            field=models.CharField(help_text='Name of the store/brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierinvitation',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
