# Generated by Django 5.2 on 2025-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_supplierinvitation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvitation',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='owner_first_name',
            field=models.CharField(default='', help_text="Owner's first name", max_length=50),
        ),
        migrations.AddField(
            model_name='supplierinvitation',
            name='owner_last_name',
            field=models.CharField(default='', help_text="Owner's last name", max_length=50),
        ),
    ]
