# Generated by Django 5.2 on 2025-10-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_add_separate_name_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvitation',
            name='store_name',
            field=models.CharField(help_text='Name of the store/brand (will be used as username)', max_length=100, unique=True),
        ),
    ]
