# Generated by Django 5.2 on 2025-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/originals/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='برند'),
        ),
    ]
