# Generated by Django 5.2.1 on 2025-05-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_brand_image'),
        ('shop', '0005_deletedproduct'),
    ]

    operations = [
    ]
