# Generated by Django 5.2 on 2025-07-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_flexible_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Single Selection'), ('multiselect', 'Multiple Selection'), ('boolean', 'Yes/No')], default='text', max_length=20, verbose_name='Attribute Type')),
                ('required', models.BooleanField(default=False, verbose_name='Is Required')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='shop.category')),
            ],
            options={
                'verbose_name': 'Category Attribute',
                'verbose_name_plural': 'Category Attributes',
                'ordering': ['display_order', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.categoryattribute')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'ordering': ['display_order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.DeleteModel(
            name='DeletedProduct',
        ),
    ]
