# Generated by Django 5.2 on 2025-07-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'key')},
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='api_key',
        ),
    ]
