# Generated by Django 5.2 on 2025-07-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_categoryattribute_label_fa'),
    ]

    operations = [
    ]
