# Generated by Django 5.2 on 2025-07-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_deletedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_image',
        ),
    ]
