# Generated by Django 5.2 on 2025-07-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='جدید / محصول جدید'),
        ),
    ]
