# Generated by Django 5.2 on 2025-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, help_text='Clean display name for frontend (e.g., "ساعت" for "ساعت مردانه")', max_length=100, verbose_name='Display Label'),
        ),
    ]
