# Generated by Django 5.2 on 2025-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_add_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_section',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('general', 'General')], help_text='Which section to show this category in (men/women/general)', max_length=20, null=True, verbose_name='Display Section'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this category in the mobile app', verbose_name='Visible in App'),
        ),
    ]
