# Generated by Django 5.2 on 2025-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_categorygender_categorygroup_category_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='shop_categories',
        ),
    ]
