# Generated by Django 5.2 on 2025-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_specialoffer_specialofferproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialofferproduct',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
