# Generated by Django 5.2 on 2025-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_specialofferproduct_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_special_offers',
            field=models.BooleanField(default=False, help_text='آیا این محصول در پیشنهادات ویژه قرار دارد؟', verbose_name='در پیشنهادات ویژه'),
        ),
    ]
