# Generated by Django 5.2 on 2025-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_add_is_in_special_offers_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialofferproduct',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='specialofferproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت اصلی'),
        ),
    ]
