# Generated by Django 5.2 on 2025-09-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_add_product_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='ترتیب نمایش تصویر (1 تا 10)', verbose_name='ترتیب'),
        ),
    ]
