# Generated by Django 5.2 on 2025-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_fix_variant_image_order_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='ترکیبی که به صورت پیش\u200cفرض نمایش داده می\u200cشود', verbose_name='ترکیب پیش\u200cفرض'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='one_default_variant_per_product'),
        ),
    ]
