# Generated by Django 5.2 on 2025-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_productvariant_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='one_default_variant_per_product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='isDistinctive',
            field=models.BooleanField(default=False, help_text='آیا این نوع محصول متمایز و خاص است؟', verbose_name='متمایز'),
        ),
    ]
