# Generated by Django 5.2 on 2025-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='is_displayed_in_product',
            field=models.BooleanField(default=True, help_text='Show this attribute in the product detail page', verbose_name='Display in Product View'),
        ),
    ]
