# Generated by Django 5.2 on 2025-10-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_add_is_displayed_in_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantimage',
            name='unique_variant_image_order',
        ),
    ]
