# Generated by Django 5.2 on 2025-10-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_remove_variant_image_order_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='display_in_basket',
            field=models.BooleanField(default=False, help_text='Show this attribute in shopping cart/basket (max 2 recommended)', verbose_name='Display in Basket'),
        ),
    ]
