# Generated by Django 5.2 on 2025-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_product_distinctive_attribute_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد تخفیف اعمال شده', max_digits=5, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='reduced_price_toman',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت تخفیف خورده محصول', max_digits=12, null=True, verbose_name='قیمت کاهش یافته (تومان)'),
        ),
    ]
