# Generated by Django 5.2 on 2025-11-06 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_add_reduced_price_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, help_text='Device ID or session key for anonymous users', max_length=100, verbose_name='کلید نشست'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer if logged in, null for anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'session_key')},
        ),
    ]
