# Generated by Django 5.2 on 2026-01-07 11:00

from django.db import migrations


def cleanup_orphaned_tags(apps, schema_editor):
    """
    Remove orphaned tag references from product-tag relationships.
    This fixes IntegrityError caused by tags that were deleted but still referenced.
    """
    # Get the through table (Product.tags.through)
    Product = apps.get_model('shop', 'Product')
    Tag = apps.get_model('shop', 'Tag')
    
    # Get the through model
    ProductTags = Product.tags.through
    
    # Get all valid tag IDs
    valid_tag_ids = set(Tag.objects.values_list('id', flat=True))
    
    # Find and delete orphaned references
    orphaned_refs = ProductTags.objects.exclude(tag_id__in=valid_tag_ids)
    count = orphaned_refs.count()
    
    if count > 0:
        orphaned_refs.delete()
        print(f"Cleaned up {count} orphaned tag reference(s)")


def reverse_func(apps, schema_editor):
    # No need to reverse this - it's a cleanup operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_orderitem_variant'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_tags, reverse_func),
    ]
