# Generated by Django 5.2.1 on 2025-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='pelak',
            field=models.CharField(blank=True, help_text='پلاک', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='vahed',
            field=models.CharField(blank=True, help_text='واحد', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='ایران', max_length=100),
        ),
    ]
