# Generated by Django 5.2 on 2025-07-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_login_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
