# Generated by Django 5.2 on 2025-07-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_address_vahed_address_phone_address_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='unit',
            new_name='vahed',
        ),
    ]
