# Generated by Django 5.2 on 2025-07-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_unit_to_vahed'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(blank=True, help_text='Name of the person receiving the package', max_length=100),
        ),
    ]
