# Generated by Django 5.2 on 2025-07-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_update_receiver_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pelak',
        ),
    ]
