# Generated by Django 5.2 on 2025-05-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage_original_image_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='original_image',
        ),
    ]
