# Generated by Django 5.2 on 2025-07-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_categoryattribute_attributevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subcategories', to='shop.attribute')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_attributes', to='shop.category')),
            ],
            options={
                'verbose_name': 'Subcategory Attribute',
                'verbose_name_plural': 'Subcategory Attributes',
                'ordering': ['display_order', 'attribute'],
                'unique_together': {('subcategory', 'attribute')},
            },
        ),
    ]
