# Generated by Django 5.2 on 2025-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_subcategoryattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'key')},
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='api_key',
            field=models.CharField(blank=True, help_text='English key for API usage', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'api_key'), ('category', 'key')},
        ),
        migrations.DeleteModel(
            name='SubcategoryAttribute',
        ),
    ]
