# Generated by Django 5.2 on 2025-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_categoryattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='label_fa',
            field=models.CharField(blank=True, help_text='Persian display label', max_length=100, null=True),
        ),
    ]
