# Generated by Django 5.2.1 on 2025-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_fill_label_fa_and_ascii_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Product attributes by key'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='label_fa',
            field=models.CharField(default='default', help_text='Persian display label', max_length=100),
            preserve_default=False,
        ),
    ]
