# Generated by Django 5.2.2 on 2025-07-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_attributes_alter_categoryattribute_label_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
