# Generated by Django 5.2.1 on 2025-07-19 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original ID of the product')),
                ('name', models.CharField(max_length=100)),
                ('price_toman', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('category_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deleted product',
                'verbose_name_plural': 'deleted products',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
