# Generated by Django 5.2 on 2025-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_add_category_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('container', 'Container Category'), ('direct', 'Direct Category'), ('auto', 'Auto-detect')], default='auto', help_text='Category behavior type', max_length=10),
        ),
    ]
