# Generated by Django 5.2 on 2025-08-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_add_visibility_and_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('unisex', 'یونیسکس'), ('general', 'عمومی')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'جنسیت دسته\u200cبندی',
                'verbose_name_plural': 'جنسیت\u200cهای دسته\u200cبندی',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('label', models.CharField(blank=True, help_text='نام تمیز برای نمایش در فرانت\u200cاند', max_length=100, verbose_name='برچسب نمایش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('supports_gender', models.BooleanField(default=True, help_text='آیا این گروه از تقسیم\u200cبندی جنسیتی پشتیبانی می\u200cکند؟', verbose_name='پشتیبانی از جنسیت')),
            ],
            options={
                'verbose_name': 'گروه دسته\u200cبندی',
                'verbose_name_plural': 'گروه\u200cهای دسته\u200cبندی',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categorygender', verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.categorygroup', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='CategorySubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیرگروه')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='برچسب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='shop.categorygroup', verbose_name='گروه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.categorysubgroup', verbose_name='زیرگروه والد')),
            ],
            options={
                'verbose_name': 'زیرگروه دسته\u200cبندی',
                'verbose_name_plural': 'زیرگروه\u200cهای دسته\u200cبندی',
                'ordering': ['display_order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.categorysubgroup', verbose_name='زیرگروه'),
        ),
    ]
