# Generated by Django 5.2 on 2025-08-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
