# Generated by Django 5.2 on 2025-08-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_update_category_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='لوگو')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='کشور')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تاسیس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand', verbose_name='برند'),
        ),
    ]
