# Generated by Django 5.2 on 2025-08-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='categorization_attribute_key',
            field=models.CharField(blank=True, help_text='کلید ویژگی که برای دسته\u200cبندی محصولات استفاده می\u200cشود (مثل: برند, رنگ, نوع حرکت). اگر خالی باشد، از اولین ویژگی موجود استفاده می\u200cشود.', max_length=100, null=True, verbose_name='کلید ویژگی دسته\u200cبندی'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
