# Generated by Django 5.2.1 on 2025-08-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_add_categorization_attribute_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='بودجه تخمینی برای خرید', max_digits=10, null=True, verbose_name='بودجه تخمینی'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='gift_message',
            field=models.TextField(blank=True, help_text='پیام هدیه', null=True, verbose_name='پیام هدیه'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='قابل مشاهده برای دیگران', verbose_name='عمومی'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True, help_text='یادداشت شخصی درباره محصول', null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], help_text='اولویت خرید', max_length=20, null=True, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='تعداد مورد نیاز', verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='تاریخ یادآوری برای خرید', null=True, verbose_name='تاریخ یادآوری'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='tags',
            field=models.JSONField(blank=True, help_text='برچسب\u200cهای شخصی', null=True, verbose_name='برچسب\u200cها'),
        ),
    ]
