# Generated by Django 5.2 on 2025-08-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_wishlist_estimated_budget_wishlist_gift_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پیشنهاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('offer_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('bundle', 'Bundle Deal'), ('discount', 'Discount'), ('free_shipping', 'Free Shipping'), ('coupon', 'Coupon'), ('seasonal', 'Seasonal Promotion'), ('clearance', 'Clearance Sale')], max_length=20, verbose_name='نوع پیشنهاد')),
                ('display_style', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('carousel', 'Carousel'), ('grid', 'Grid Layout'), ('sidebar', 'Sidebar'), ('popup', 'Popup Modal')], max_length=20, verbose_name='سبک نمایش')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='special_offers/banners/', verbose_name='تصویر بنر')),
                ('banner_action_type', models.CharField(choices=[('product', 'Product Page'), ('category', 'Category Page'), ('search', 'Search Results'), ('external', 'External Link'), ('none', 'No Action')], default='none', max_length=20, verbose_name='نوع عملیات بنر')),
                ('banner_action_target', models.CharField(blank=True, max_length=500, verbose_name='هدف عملیات بنر')),
                ('banner_external_url', models.URLField(blank=True, verbose_name='لینک خارجی')),
                ('valid_from', models.DateTimeField(verbose_name='شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_active', models.BooleanField(default=True, verbose_name='در حال اجرا')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کلیک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیشنهاد ویژه',
                'verbose_name_plural': 'پیشنهادات ویژه',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت اصلی')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت با تخفیف')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.specialoffer', verbose_name='پیشنهاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول پیشنهاد ویژه',
                'verbose_name_plural': 'محصولات پیشنهادات ویژه',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('offer', 'product')},
            },
        ),
    ]
