# Generated by Django 5.2 on 2025-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_fix_decimal_field_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='newattributevalue',
            name='persian_label',
            field=models.CharField(blank=True, help_text='برچسب فارسی برای نمایش در رابط کاربری', max_length=100, null=True, verbose_name='برچسب فارسی'),
        ),
    ]
