# Generated by Django 5.2.2 on 2025-09-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_add_persian_label_to_attribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='کد محصول')),
                ('attributes', models.JSONField(default=dict, help_text='ویژگی\u200cهای این نوع محصول (رنگ، سایز و...)', verbose_name='ویژگی\u200cها')),
                ('price_toman', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصول',
                'ordering': ['sku'],
            },
        ),
    ]
