# Generated by Django 5.2 on 2025-09-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_images/', verbose_name='تصویر')),
                ('is_primary', models.BooleanField(default=False, help_text='تصویر اصلی این نوع محصول', verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش تصویر (1 تا 10)', verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('image_hash', models.CharField(blank=True, help_text='هش یکتا برای تشخیص تصاویر تکراری', max_length=64, null=True, verbose_name='هش تصویر')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant', verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'تصویر نوع محصول',
                'verbose_name_plural': 'تصاویر انواع محصول',
                'ordering': ['-is_primary', 'order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'order'), name='unique_variant_image_order'), models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 10)), name='variant_image_order_range')],
            },
        ),
    ]
