"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _get_list_from_env(var_name: str, default: list[str]) -> list[str]:
    """
    Parse a comma-separated environment variable into a stripped list.
    Falls back to the provided default when the variable is missing or empty.
    """
    raw = os.environ.get(var_name, '')
    if not raw:
        return default
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^v*!9s+@i%_0bp^%f00ak=&e04cdkbs1z@v-_ugelq8=!3r$4&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

# Default to local-only hosts; override via ALLOWED_HOSTS env var for other domains
ALLOWED_HOSTS = _get_list_from_env(
    'ALLOWED_HOSTS',
    ['127.0.0.1', 'localhost'],
)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Required for token blacklisting
    'corsheaders',  # Added CORS headers
    
    # Local apps
    'accounts',
    'suppliers',
    'image_editor',
    'shop',  # Added shop app
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Added CORS middleware
    'shop.middleware.GlobalRateLimitMiddleware',  # Global rate limiting for all endpoints
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = 'accounts:login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'

# Database
# Check for DATABASE_URL (set by Render and other platforms)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production database (PostgreSQL on Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Ensure ENGINE is set (fallback if dj_database_url fails)
    if not DATABASES['default'].get('ENGINE'):
        DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
else:
    # Local SQLite database (development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration
# Use local memory cache for rate limiting (works on Render)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20MB

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hamiltonwatchbrands@gmail.com'
EMAIL_HOST_PASSWORD = 'npkj lzmr xdbi vpfi'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Site URL for invitation links
SITE_URL = 'http://127.0.0.1:8000'

# Custom User Model
AUTH_USER_MODEL = 'accounts.Customer'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'accounts.backends.CustomerBackend',
    'suppliers.backends.SupplierAuthenticationBackend',
]

SITE_ID = 1

# AllAuth settings
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_LOGIN_METHODS = {'email'}  # Only allow email login
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Updated AllAuth settings (new format)
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/accounts/login/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  # For admin users
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # For API users
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Changed from 3 minutes to 24 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),  # 90 days for better user experience
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'LEEWAY': 60,  # Allow up to 60 seconds of clock skew
}

# Session Configuration for better authentication persistence
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session alive after browser close
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_SECURE = False  # Set to False for local development
CSRF_COOKIE_SECURE = False  # Set to False for local development
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests

# Security settings
if 'RENDER' in os.environ:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CORS settings
DEFAULT_LOCAL_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

CORS_ALLOWED_ORIGINS = _get_list_from_env(
    'CORS_ALLOWED_ORIGINS',
    DEFAULT_LOCAL_ORIGINS,
)

# CSRF settings for Django 4.0+
CSRF_TRUSTED_ORIGINS = _get_list_from_env(
    'CSRF_TRUSTED_ORIGINS',
    DEFAULT_LOCAL_ORIGINS,
)

# Allow all headers and methods for development
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": ""
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
}

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_IOS_CLIENT_ID", "")
GOOGLE_CLIENT_IDS = [
    os.environ.get("GOOGLE_IOS_CLIENT_ID", ""),
    os.environ.get("GOOGLE_WEB_CLIENT_ID", ""),
]

# ============================================================================
# PASSWORD HASHING - OPTIMIZED FOR RENDER
# ============================================================================
# Django's default PBKDF2 uses 320,000 iterations which takes 3-4s on Render's CPU
# We reduce to 100,000 for faster login while maintaining strong security
# This still exceeds OWASP minimum recommendation of 10,000 iterations

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# Override default iteration count for faster performance on limited CPU
# Default: 320,000 iterations (~3-4s on Render's starter tier)
# Custom:  100,000 iterations (~1s on Render's starter tier)
# Note: Existing passwords auto-upgrade on next login
import django.contrib.auth.hashers as hashers
hashers.PBKDF2PasswordHasher.iterations = 100000

# ============================================================================
# LOGIN SECURITY SYSTEM CONFIGURATION
# ============================================================================

# Security Tier Thresholds (Number of Failed Attempts)
LOGIN_SECURITY_TIER_1_MAX = 3          # Tier 1: Normal (0-3 attempts)
LOGIN_SECURITY_TIER_2_MAX = 5          # Tier 2: Warning + delay (4-5 attempts)
LOGIN_SECURITY_TIER_3_MAX = 8          # Tier 3: CAPTCHA required (6-8 attempts)
LOGIN_SECURITY_TIER_4_MAX = 10         # Tier 4: Email verification (9-10 attempts)
LOGIN_SECURITY_TIER_5_LOCK = 11        # Tier 5: Account lock (11+ attempts)

# Progressive Delays (in seconds) - SET TO 0 FOR FAST LOGIN
LOGIN_SECURITY_TIER_2_DELAY = 0        # No delay (was 2s)
LOGIN_SECURITY_TIER_3_DELAY = 0        # No delay (was 5s)
LOGIN_SECURITY_TIER_4_DELAY = 0        # No delay (was 10s)

# Time Windows for Attempt Counting
LOGIN_SECURITY_MINUTE_WINDOW = 60      # 1 minute in seconds
LOGIN_SECURITY_HOUR_WINDOW = 3600      # 1 hour in seconds
LOGIN_SECURITY_DAY_WINDOW = 86400      # 24 hours in seconds

# Rate Limiting
LOGIN_SECURITY_MAX_PER_MINUTE = 20     # Max 20 login attempts per minute (increased so tier system can work)
LOGIN_SECURITY_MAX_PER_HOUR = 40       # Max 40 login attempts per hour per IP
LOGIN_SECURITY_MAX_PER_DAY = 11        # Max 11 failed attempts per day per email (triggers Tier 5 lock)

# Lock Settings
LOGIN_SECURITY_ACCOUNT_LOCK_HOURS = 1  # Account locked for 1 hour
LOGIN_SECURITY_IP_BLOCK_HOURS = 24     # IP blocked for 24 hours

# Fast Attack Detection (Speed-based)
LOGIN_SECURITY_FAST_ATTACK_THRESHOLD = 10   # 10 attempts
LOGIN_SECURITY_FAST_ATTACK_WINDOW = 120     # in 2 minutes = obvious attack

# Verification Code Settings
LOGIN_SECURITY_CODE_LENGTH = 6              # 6-digit code
LOGIN_SECURITY_CODE_EXPIRY_MINUTES = 10     # Code expires in 10 minutes
LOGIN_SECURITY_CODE_MAX_ATTEMPTS = 3        # Max 3 verification attempts

# Unlock Token Settings
LOGIN_SECURITY_UNLOCK_TOKEN_EXPIRY_HOURS = 24  # Token valid for 24 hours

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

# S3 Storage Configuration - DISABLED: Using local media folder from Git instead
# if 'RENDER' in os.environ:
#     # Use S3 for media files in production
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     
#     # S3 Configuration
#     AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
#     AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
#     AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
#     AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
#     
#     # Optional: Improve performance and reduce costs
#     AWS_S3_FILE_OVERWRITE = True
#     AWS_DEFAULT_ACL = None
#     AWS_QUERYSTRING_AUTH = False
#     
#     # Optional: Set a custom domain for your S3 bucket
#     # AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
